### ISSUE TITLE
Error after update 

### ISSUE THREAD

**Issue by bladerunner82** [phate89/plugin.video.videomediaset#1]
After the Update ....when trying to enter the addon its giving me an error message
Please can y fix that 

Grazie

**Comment by phate89** [comment]
without a log I can't do anything..

**Comment by bladerunner82** [comment]
https://paste.ubuntu.com/23757282/

**Comment by bladerunner82** [comment]
Can y See the error in this Log

**Comment by phate89** [comment]
sure. can you try to install this:
https://github.com/phate89/script.module.phate89/releases/download/1.0.1/script.module.phate89.v1.0.1.zip

**Comment by bladerunner82** [comment]
Si adesso funziona :)
Thanks  :) ....it s working now

**Comment by Mico609** [comment]
I am haveing the same issue on amazon fire stick.  I do not know how to install "https://github.com/phate89/script.module.phate89/releases/download/1.0.1/script.module.phate89.v1.0.1.zip"  for kodi on fire stick.  Please help.  Fix error issues.
