### ISSUE TITLE
"This video is not Available for your country"

### ISSUE THREAD

**Issue by andrellibus** [phate89/plugin.video.videomediaset#11]
Hi, 
I'm having  problems with all videos after april 12th (regardless of the show), when i try to play them i get a 10 sec video instead saying
"Questo video non è disponibile per il tuo paese
This video is not Available for your country"
(I live in italy)

If I try to access them from a browser they work fine and also I can play videos before april 12th from the addon without any problems...so i'm not sure what's going on.

Am i the only one with this issue?

**Comment by sissensio** [comment]
Hi, I have exactly the same problem too.
Anche io ho lo stesso esatto problema. Assieme ad altri amici che usano Kodi.
Praticamente è come se l'IP che arriva ai server di mediaset per lo streaming non fosse italiano e fosse fuori dall'Italia. Forse colpa di qualche resolver? Proxy? non saprei.

**Comment by fabandroid** [comment]
Ok I have the same issue here!
I'm in Miami and before there was not problem.
So I saw the banner of outside from italy and through a VPN server in Italy with Italian IP I have the same problem!
Fatemi sapere come mai e come risolvere questo problema e se devo usare una VPN con ip Italiano.
Grazie.
Siete Grandi!

**Comment by dimi90** [comment]
Seguo anch io,
Stesso problema purtroppo!

**Comment by franpic** [comment]
Anche io ho lo stesso problema

**Comment by alexdotnet** [comment]
Stesso problema

**Comment by garret** [comment]
Anche io ho lo stesso problema. Uso Libreelec su un raspberry pi vecchio modello.

**Comment by I8NHJ** [comment]
Mi aggiungo alla lista di chi ha il problema.
Grazie

**Comment by jokerulez** [comment]
Per tutti gli interessati, sembrerebbe esserci una versione più aggiornata basta su questa e funzionanten. Se ne parla sul gruppo telegram @kodiitalia, sul forum ufficiale di kodi https://forum.kodi.tv/showthread.php?tid=292876&pid=2730359#pid2730359 e si trova sul github qui: https://github.com/fsponga/plugin.video.videomediaset/releases

**Comment by I8NHJ** [comment]
Hello jokerulez,
Thank you for the info. I updated the plug-in yesterday night and indeed it is working.
The images quality seems very poor, though.

Best Regards,
Massimo Mucci

Monday, April 30, 2018, 6:54:12 AM, you wrote:

**Comment by phate89** [comment]
Fixed it
