### ISSUE TITLE
Diretta canali live

### ISSUE THREAD

**Issue by gattomatto69** [phate89/plugin.video.videomediaset#15]
Ciao,

Probabilmente con il discorso dei mondiali devono aver cambiato qualcosa nella diretta live e nemmeno con VPN e server Italiano si riesce a vedere da Kodi; sul sito invece tutto funziona correttamente con VPN.

Grazie

**Comment by FezVrasta** [comment]
It's not working neither with the version released today (1.3.2)

**Comment by rewe68** [comment]
In addition to FezVrasta comment, also video links are not working. Only selectable, but not playable

**Comment by gattomatto69** [comment]
The update solved the issue for me. If you are not in Italy, you need to use a VPN and connect to an Italian server. This is because Mediaset is restricting the live channels to Italian IPs only.
