### ISSUE TITLE
Start addon issuse

### ISSUE THREAD

**Issue by CWlf** [phate89/plugin.video.videomediaset#2]
Hi,
when I try to start "Videomediaset" Kodi tell me there is an error (View Log for more information). :(

I had 1.1.3 version; I have upgraded to 1.2.0 but I have same issue! 

kodi.log:
`23:02:52 T:1928610752   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named simplejson
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.videomediaset/default.py", line 3, in <module>
                                                from phate89lib import kodiutils, staticutils
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.phate89/lib/phate89lib/kodiutils.py", line 12, in <module>
                                                import simplejson as json
                                            ImportError: No module named simplejson
                                            -->End of Python script error report<--
23:02:52 T:1789219280   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.videomediaset/
23:02:52 T:1789219280   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.videomediaset/) failed
23:06:17 T:1789219280  NOTICE: GL_VENDOR = ARM
23:06:17 T:1789219280  NOTICE: GL_RENDERER = Mali-450 MP
23:06:17 T:1789219280  NOTICE: GL_VERSION = OpenGL ES 2.0
23:06:17 T:1789219280  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
23:06:17 T:1789219280  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug
`

**Comment by phate89** [comment]
I already pushed an update that shouls solve this. anyway you should post the full log the next time so I cansee addon versions
