### ISSUE TITLE
Strart program fail

### ISSUE THREAD

**Issue by CWlf** [phate89/plugin.video.videomediaset#3]
If I try to start:
"Elenco programmi/I/Il segreto/PUNTATE INTERE" and I select Mercoledi 15 or Giovedi 16 they don't start. If I select a previus episode they start correctly.

I don't understand why the last one don't start; can you help me?

Thanks!

**Comment by Gioherk** [comment]
Same problem here.
I can't play any of the recent videos but I have no problem with the old ones.
Here is my debug log: [http://paste.semperpax.com/ptmksjvxe](url)

**Comment by phate89** [comment]
It should be fixed with:
https://github.com/phate89/plugin.video.videomediaset/releases/download/1.2.1/plugin.video.videomediaset.v1.2.1.zip

**Comment by Gioherk** [comment]
With v1.2.1 everything is ok.
Thanks

**Comment by alessandroniciforo** [comment]
I can confirm it works on 1.2.1 as well.
Thanks @phate89 for supporting this plugin.

**Comment by CWlf** [comment]
New blackout! :(
Now I can't play the recent videos and the old too! :(

**Comment by Tux92** [comment]
Same here, when I try to load last episode no problem, but when you select elenco programmi and then a program it will fail. ;(
